post http://localhost:3000/signup
Content-Type: application/json

{
  "email": "iliyaa7@gmail.com",
  "password": "5792",
  "name": "iliya",
  "about": "gomon",
  "avatar": "https://code.s3.yandex.net/web-code/bald-mountains.jpg"
}

###

post http://localhost:3000/signin
Content-Type: application/json

{
  "email": "iliyaagmail.com",
  "password": "5792"
}

###

get http://localhost:3000/cards
Authorization: Bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjA2YWU0NTVhNDk3NGE0ZmVjZDlmYmQiLCJpYXQiOjE2NDQ2NzM2NDMsImV4cCI6MTY0NTI3ODQ0M30.DHxrdYDESTURYD-rh_QsHZT_FJOskjQU061VO65ps7w

###

post http://localhost:3000/cards
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjA2YWU0NTVhNDk3NGE0ZmVjZDlmYmQiLCJpYXQiOjE2NDQ2NzM2NDMsImV4cCI6MTY0NTI3ODQ0M30.DHxrdYDESTURYD-rh_QsHZT_FJOskjQU061VO65ps7w

{
  "name": "test card 1",
  "link": "https://code.s3.yandex.net/web-code/bald-mountains.jpg"
}
###

delete http://localhost:3000/cards/62095d65ad2ba223e86c2cf8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjA2YWU0NTVhNDk3NGE0ZmVjZDlmYmQiLCJpYXQiOjE2NDQ2NzM2NDMsImV4cCI6MTY0NTI3ODQ0M30.DHxrdYDESTURYD-rh_QsHZT_FJOskjQU061VO65ps7w

###

put http://localhost:3000/cards/62084ea7773885cf16dc01fc/likes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjA3YmUyNzEzODYxZjExZGMyOGVkOWEiLCJpYXQiOjE2NDQ3MTA0MjAsImV4cCI6MTY0NTMxNTIyMH0.ix6XDETbcnxN-f0SBpzLL97atNEsLCgRG50JLd7Cj5M

###

delete http://localhost:3000/cards/62084ea7773885cf16dc01fc/likes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjA3YmUyNzEzODYxZjExZGMyOGVkOWEiLCJpYXQiOjE2NDQ2NzQ2MTcsImV4cCI6MTY0NTI3OTQxN30.PuGih88WAmhq4VFRHX2GDBs5dz9aWHxb_e3nrB8goBw

###

get http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjA2YWU0NTVhNDk3NGE0ZmVjZDlmYmQiLCJpYXQiOjE2NDQ2NzM2NDMsImV4cCI6MTY0NTI3ODQ0M30.DHxrdYDESTURYD-rh_QsHZT_FJOskjQU061VO65ps7w

###

get http://localhost:3000/users/me
Authorization: Bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjA3YmUyNzEzODYxZjExZGMyOGVkOWEiLCJpYXQiOjE2NDQ2NzQ2MTcsImV4cCI6MTY0NTI3OTQxN30.PuGih88WAmhq4VFRHX2GDBs5dz9aWHxb_e3nrB8goBw

###

patch http://localhost:3000/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjA3YmUyNzEzODYxZjExZGMyOGVkOWEiLCJpYXQiOjE2NDQ2NzQ2MTcsImV4cCI6MTY0NTI3OTQxN30.PuGih88WAmhq4VFRHX2GDBs5dz9aWHxb_e3nrB8goBw

{
  "name": "patched user 5",
  "about": "patched 4"
}

###

patch http://localhost:3000/users/me/avatar
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjA3YmUyNzEzODYxZjExZGMyOGVkOWEiLCJpYXQiOjE2NDQ2NzQ2MTcsImV4cCI6MTY0NTI3OTQxN30.PuGih88WAmhq4VFRHX2GDBs5dz9aWHxb_e3nrB8goBw

{
  "avatar": "https://code.s3.yandex.net/web-code/ccccc.jpg"
}